name: CI and Build package
'on':
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
jobs:
  ci_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean Install
        run: npm ci
      - name: Unit tests
        run: npm run test
      - name: Build
        run: npm run build
